name: Trigger CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger External CI/CD Repo
        run: |
          curl -X POST https://api.github.com/repos/<ORG_OR_USERNAME>/salesforce-cicd-pipeline/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PIPELINE_TRIGGER_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{
            "event_type": "salesforce_deploy",
            "client_payload": {
              "source_repo": "salesforce-demo",
              "branch": "${{ github.ref_name }}",
              "commit_id": "${{ github.sha }}"
            }
          }'
